### ISSUE TITLE
Margin top op button 'essentiële cookies' geeft te veel margin

### ISSUE THREAD

**Issue by SarahOorts** [statikbe/craft-cookie-banner#6]
mt-6 geeft te veel margin op lijn 11 van https://github.com/statikbe/craft-cookie-banner/blob/develop/src/templates/_banner.twig.

**Comment by carolineboeykens** [comment]
Ik heb dit mee aangepast in https://github.com/statikbe/craft-cookie-banner/commit/0e6a4d99b56462503048a18b4805434ef8440361
